version: '1'
services:
  flask:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - "6380:6379"